package main

import (
	"frs-its-backend/config"
	"frs-its-backend/controllers"
	_ "frs-its-backend/docs" // generated by swag

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title FRS Mahasiswa API
// @version 1.0
// @description API untuk sistem Formulir Rencana Studi Mahasiswa ITS
// @host localhost:8080
// @BasePath /
func main() {
	config.ConnectDB()

	r := gin.Default()

	// Izinkan CORS agar Next.js (port 3000) bisa akses Golang (port 8080)
	r.Use(cors.Default())

	// Swagger Endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API Routes
	api := r.Group("/api")
	{
		api.POST("/login", controllers.Login) // <-- Tambahkan ini
		api.GET("/courses", controllers.GetCourses)
		api.POST("/frs/enroll", controllers.EnrollCourse)
		api.GET("/frs/:student_id", controllers.GetStudentFRS)
		api.DELETE("/frs/:id", controllers.DropCourse)
	}

	r.Run(":8080")
}
